-- Alle Sitzungen verwerfen — einmalig, mit dem Umschalten auf die neue
-- Oberfläche (0.4.0).
--
-- Warum überhaupt: Eine laufende Sitzung ist an eine Oberfläche gebunden, die es
-- nach dem Update nicht mehr an derselben Stelle gibt. Der sichtbare Teil davon
-- ist harmlos — ein offener Browser bekommt beim nächsten Klick die neue Fläche.
-- Der unsichtbare ist es nicht: Das Sitzungstoken der alten Oberfläche steckt in
-- jeder gerenderten Seite, die noch im Browser steht, und ein Formular von dort
-- schickt es an Pfade, die jetzt woanders liegen. Was dabei herauskommt, ist
-- nicht falsch, aber es ist auch nicht vorhersagbar, und ein Anmeldevorgang ist
-- der billigste Weg, den ganzen Zustand einmal auf null zu setzen.
--
-- Der zweite Grund ist ehrlicher: Ein Update, das die Oberfläche austauscht, ist
-- der richtige Zeitpunkt, jeden Zugang einmal nachweisen zu lassen. Wer ein
-- Cookie von vor dem Update hat, hat es aus einer Zeit, in der das Panel anders
-- aussah.
--
-- Was NICHT verworfen wird: die API-Tokens. Sie hängen nicht an einer Oberfläche,
-- sondern an /api/v1 — und das ist unverändert. Ein Token zu verwerfen hieße,
-- jede Automatisierung mit einem Update abzuschalten, und zwar stillschweigend.
-- Genau davor warnt das Panel beim Zurücksetzen eines Zugangs; hier gilt es
-- ebenso.
--
-- Diese Migration läuft genau einmal. Ein späteres Update verwirft keine
-- Sitzungen mehr — dafür gibt es die Frist und den Handgriff auf der Kontoseite.
DELETE FROM sessions;
